name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - uses: pnpm/action-setup@v3
        with:
          version: 10.15.0
          run_install: false

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@10.15.0 --activate

      - name: Activate pnpm
        run: corepack prepare pnpm@10.15.0 --activate

      # (Opcional) Instala primero para calentar caché
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build & Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_02B18230F }}
          action: upload

          # 👇 Ajusta rutas según tu repo
          app_location: apps/web            # carpeta del frontend
          output_location: .next            # Next.js: usa ".next", Vite/CRA: "dist" o "build"

          # Fuerza build con pnpm (Oryx ejecutará esto)
          app_build_command: pnpm build

          # Si tienes API Node separada en el monorepo:
          # api_location: apps/api
          # api_build_command: pnpm --filter ./apps/api... install --frozen-lockfile && pnpm --filter ./apps/api... build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
